# Generated by Django 6.0.6 on 2026-06-05 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email professionnel')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Photo de profil')),
                ('poste', models.CharField(choices=[('stagiaire', 'Stagiaire'), ('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager'), ('directeur', 'Directeur')], max_length=20, verbose_name='Niveau hiérarchique')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], max_length=20, verbose_name='Type de contrat')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('statut', models.CharField(default='actif', max_length=20, verbose_name='Statut')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='diplomes/', verbose_name='Diplôme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='Département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
