# Generated by Django 6.0.6 on 2026-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_urgence',
            field=models.CharField(default=1, help_text='Ex: Nom - Numéro de téléphone - Lien de parenté', max_length=100, verbose_name="Contact d'urgence"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='etat_civil',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, verbose_name='État civil'),
        ),
        migrations.AddField(
            model_name='employee',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
