# Generated by Django 6.0.6 on 2026-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_contact_urgence_employee_etat_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='niveau',
            field=models.CharField(choices=[('stagiaire', 'Stagiaire'), ('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager'), ('directeur', 'Directeur')], default='junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.CharField(choices=[('responsable_rh', 'Responsable RH'), ('comptable', 'Comptable'), ('charge_marketing', 'Chargée Marketing'), ('commercial', 'Commercial'), ('responsable_logistique', 'Responsable Logistique'), ('assistant_administratif', 'Assistant Administratif'), ('chauffeur', 'Chauffeur'), ('agent_entretien', "Agent d'entretien")], max_length=100, verbose_name='Niveau hiérarchique'),
        ),
    ]
