# Generated by Django 6.0.6 on 2026-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_alter_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prime'),
        ),
    ]
