# Generated by Django 6.0.6 on 2026-06-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RH', 'RH'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=20),
        ),
    ]
